name: n1
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  bloc: ^8.1.2
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.7
  flutter_rounded_progress_bar: ^0.3.2
  gradient_widgets: ^0.6.0
  inner_shadow_widget: ^0.0.3
  flutter_inset_box_shadow: ^1.0.8
  flame_audio: ^2.1.7
  webview_flutter: ^4.4.4
  share_plus: ^7.2.1
  in_app_review: ^2.0.8
  url_launcher: ^6.2.4
  flutter_keyboard_visibility: ^6.0.0
  stroke_text: ^0.0.2
  circular_countdown_timer: ^0.2.3
  theme_provider: ^0.6.0
  lottie: ^3.0.0
  flutter_local_notifications: ^16.3.2
  flame: ^1.16.0
  flutter_fortune_wheel: ^1.3.1
  pausable_timer: ^3.1.0+3
  flutter_screenutil: ^5.9.0
  expandable_page_view: ^1.0.17
  step_progress_indicator: ^1.0.2
  animate_do: ^3.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.0.3+1
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/


  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-Bold.ttf
        - asset: fonts/Manrope-ExtraBold.ttf
        - asset: fonts/Manrope-ExtraLight.ttf
        - asset: fonts/Manrope-Light.ttf
        - asset: fonts/Manrope-Medium.ttf
        - asset: fonts/Manrope-Regular.ttf
        - asset: fonts/Manrope-SemiBold.ttf






